server:
  port: 8090

logging:
  level:
    com.artemnizhnyk: DEBUG
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/smtp_repository
    username: postgres
    password: 4253

  jpa:
    hibernate:
      ddl-auto: update